services:
  # Frontend servisi
  frontend:
    build:
      context: .  # Projenin ana dizinini kullan
      dockerfile: frontend.Dockerfile # Hangi Dockerfile'ı kullanacağını belirt
    ports:
      - "5173:80" # Dışarıdaki 5173 portunu, içerideki Nginx'in 80 portuna yönlendir
    networks:
      - app-network

  # Backend servisi
  backend:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8011 --reload
    ports:
      - "8011:8011"
    volumes:
      - ./app:/app
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=catering_project_db
    depends_on:
      - mongo
    networks:
      - app-network

  # MongoDB servisi
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge